modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="icon.png"
issueTrackerURL="https://github.com/ssbaxys/create-warnautics/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayURL="https://github.com/ssbaxys/create-warnautics"
displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="createbigcannons"
    type="required"
    versionRange="${cbc_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="sable"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="simulated"
    type="optional"
    versionRange="[1.2.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="offroad"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="veil"
    type="optional"
    versionRange="[4.0,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="sable_player_ragdoll"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="ragdoll_reactions"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
