import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const modelDir = resolve(root, "src/main/resources/assets/cbc_more_content/models/block");

const readJson = (name) =>
  JSON.parse(readFileSync(resolve(modelDir, name), "utf8"));
const writeJson = (name, data) =>
  writeFileSync(resolve(modelDir, name), `${JSON.stringify(data, null, 2)}\n`, "utf8");

const sea = readJson("sea_bomb.json");
writeJson("sea_bomb_body.json", {
  ...sea,
  credit: "Author sea-bomb model; projectile body split generated by Warnautics",
  elements: sea.elements.filter((element) => element.name !== "propeller_hub"),
});
writeJson("sea_bomb_rotor.json", {
  ...sea,
  credit: "Author sea-bomb propeller; animated projectile rotor split generated by Warnautics",
  elements: sea.elements.filter((element) => element.name === "propeller_hub"),
});

const small = readJson("small_bomb.json");
const layouts = new Map([
  [2, [[-4.25, 0.0], [4.25, 0.0]]],
  [3, [[-4.5, -3.0], [4.5, -3.0], [0.0, 4.5]]],
  [4, [[-4.25, -4.25], [4.25, -4.25], [-4.25, 4.25], [4.25, 4.25]]],
]);

function shiftedElement(element, dx, dz) {
  const copy = structuredClone(element);
  copy.from[0] += dx;
  copy.from[2] += dz;
  copy.to[0] += dx;
  copy.to[2] += dz;
  if (copy.rotation?.origin) {
    copy.rotation.origin[0] += dx;
    copy.rotation.origin[2] += dz;
  }
  return copy;
}

function brace(from, to) {
  const face = { uv: [0, 0, 16, 16], texture: "#rod" };
  return {
    name: "cassette_brace",
    from,
    to,
    faces: {
      north: face,
      east: face,
      south: face,
      west: face,
      up: face,
      down: face,
    },
  };
}

for (const [count, offsets] of layouts) {
  const elements = offsets.flatMap(([dx, dz]) =>
    small.elements.map((element) => shiftedElement(element, dx, dz)));

  // Thin full-span straps visually bind the full-size bombs without scaling them.
  elements.push(brace([-2.0, 7.65, 7.7], [18.0, 8.35, 8.3]));
  if (count >= 3) {
    elements.push(brace([7.7, 7.65, -2.0], [8.3, 8.35, 18.0]));
  }

  writeJson(`small_bomb_cassette_${count}.json`, {
    ...small,
    credit: `Full-size ${count}-bomb cassette generated from the author small-bomb model`,
    textures: {
      ...small.textures,
      rod: "cbc_more_content:block/cassette_rod",
    },
    elements,
  });
}
